const faqData = [
  { q: "1. Quem é MC Paiva?", a: "Um dos grandes nomes do funk paulista atual, conhecido por diversos sucessos e ostentação." },
  { q: "2. Quem é Anny Bergatin (Malévola)?", a: "Influenciadora digital e criadora de conteúdo muito popular nas redes sociais." },
  { q: "3. Qual foi a origem do desentendimento entre os dois?", a: "A polêmica começou após trocas de indiretas nas redes sociais envolvendo exposições pessoais." },
  { q: "4. A briga ocorreu em qual plataforma principal?", a: "Principalmente nos Stories do Instagram e repercutiu no X (antigo Twitter) e TikTok." },
  { q: "5. Houve vazamento de conversas de WhatsApp?", a: "Sim, trechos de prints de conversas privadas foram publicados na internet." },
  { q: "6. Qual foi o estopim da discussão?", a: "Comentários sobre relacionamentos passados e acusações de falsidade de ambas as partes." },
  { q: "7. MC Paiva se pronunciou oficialmente?", a: "Sim, ele gravou vídeos nos Stories tentando explicar o seu lado da história." },
  { q: "8. Malévola respondeu às declarações dele?", a: "Sim, ela abriu lives e fez postagens rebatendo ponto a ponto as falas do cantor." },
  { q: "9. O assunto chegou a ficar nos Trend Topics?", a: "Sim, o nome dos dois ocupou os assuntos mais comentados no Brasil por dias." },
  { q: "10. Teve envolvimento de outros influenciadores?", a: "Diversos amigos de ambas as partes comentaram o caso, aumentando a repercussão." },
  { q: "11. Qual foi a reação dos fãs de MC Paiva?", a: "Muitos defenderam o cantor afirmando que as falas foram retiradas de contexto." },
  { q: "12. Qual foi a reação dos seguidores de Malévola?", a: "A apoiaram e criticaram a postura das postagens feitas em relação a ela." },
  { q: "13. A briga envolveu questões financeiras?", a: "Parte da discussão envolveu cobranças e especulações sobre ajuda financeira e status." },
  { q: "14. Eles já tinham proximidade antes da briga?", a: "Sim, ambos conviviam no mesmo círculo de influenciadores e eventos do funk." },
  { q: "15. Houve pedido de desculpas público?", a: "Algumas declarações posteriores tentaram amenizar, mas o clima permaneceu tenso." },
  { q: "16. Páginas de fofoca cobriram o caso?", a: "Sim, perfis como Gossip do Dia e Choquei postaram atualizações constantes." },
  { q: "17. A polêmica afetou lançamentos de músicas?", a: "Gerou bastante engajamento e atenção para o perfil do cantor durante o período." },
  { q: "18. Malévola perdeu ou ganhou seguidores?", a: "A repercussão gerou um grande pico de visualizações e novos seguidores no perfil dela." },
  { q: "19. O caso envolveu medidas judiciais?", a: "Houve boatos sobre processos por danos morais, mas sem confirmação formal detalhada nas redes." },
  { q: "20. O vídeo no topo do site fala sobre o quê?", a: "Mostra o resumo e a análise dos principais pontos da polêmica exibidos na internet." },
  { q: "21. A briga durou quanto tempo na internet?", a: "O pico da discussão durou cerca de uma semana intensa de publicações." },
  { q: "22. Eles apagaram os Stories da discussão?", a: "Sim, como é comum na rede, a maioria dos Stories expirou ou foi apaga posteriormente." },
  { q: "23. Houve acusação de marketing?", a: "Parte do público especulou que a briga poderia ser estratégia de marketing, o que foi negado." },
  { q: "24. Onde encontrar o vídeo completo?", a: "Clicando no link de destaque no topo deste site você vai direto ao YouTube." },
  { q: "25. Quem postou os primeiros prints?", a: "A exposição inicial partiu de desabafos feitos nos próprios perfis pessoais." },
  { q: "26. Houve vazamento de áudios?", a: "Áudios com tom de voz alterado circularam em canais do Telegram e TikTok." },
  { q: "27. Qual foi o tom das declarações da Malévola?", a: "Ela adotou um tom firme de indignação com as acusações." },